# Generated by Django 3.1.2 on 2020-10-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name.', max_length=50)),
                ('description', models.TextField(help_text='Enter a description of course.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an address.', max_length=50)),
                ('description', models.TextField(help_text='Enter a description of speciality.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of student.', max_length=100)),
                ('date_birth', models.DateTimeField(help_text='Enter a date birth of student.')),
                ('address', models.CharField(help_text='Enter an address.', max_length=50)),
                ('course', models.ManyToManyField(to='catalog.Course')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(to='catalog.Speciality'),
        ),
    ]
